### ISSUE TITLE
CRF

### ISSUE THREAD

**Issue by liuyi1989** [AceCoooool/DSS-pytorch#1]
Do you have the implementation with CRF for this paper in python?

**Comment by AceCoooool** [comment]
I have not implement this. (as a post-process, you can use "third-library" to deal with it) 
There are several implementation of CRF:
[pytorch-crf](https://github.com/kmkurn/pytorch-crf)
[crf using by official DSS implement](https://github.com/Andrew-Qibin/dss_crf)

**Comment by liuyi1989** [comment]
Thank you! Besides, would you send me your pretrained model without CRF? This is helpful for my research.

**Comment by AceCoooool** [comment]
I did not train in the official dataset (just use ECSSD dataset as an example), you can train it by yourself (Not cost too many time)。 Sure, if you want a trained model, i can send it to you later (this evening, whould you mind to provide you email) --- :joy: I did not do this for a long time, so I recommend you to train it by yourself.

**Comment by liuyi1989** [comment]
Sorry to my late reply. My mail: yLiu_89@stu.xidian.edu.cn. Thank you very much!

**Comment by AceCoooool** [comment]
@liuyi1989 I am sorry for reply so later. I have update the code, and the pre-trained model will put tomorrow（v2 is still in training in my computer）
