### ISSUE TITLE
the demo.py

### ISSUE THREAD

**Issue by kunfei1** [AceCoooool/DSS-pytorch#3]
There is  a command in Readme.md need demo.py, but I can't find the project. would you send me the code of that? I just learn it recencently ,not familiarly。。。

**Comment by AceCoooool** [comment]
The code of demo is similar to "test" phase, you can write it by yourself. (I am sorry, i delete the demo code in my own computer.---I will update this code in the future)

**Comment by eram1205** [comment]
Hi @kunfei1 @AceCoooool ! I did a demo.py, I can create a PR if you give me access rights.

**Comment by AceCoooool** [comment]
@eram1205 OK，thanks for your help !

**Comment by kunfei1** [comment]
@eram1205 Thank you！

**Comment by AceCoooool** [comment]
@kunfei1  I have add the demo. （the pre-trained model will provide tomorrow）
